### PR TITLE
update html-minifier version

### PR DESCRIPTION
**Pull request by igoradamenko**
https://github.com/jonschlinkert/gulp-htmlmin/issues/48

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by jonschlinkert** [comment]
want to update unit tests too? otherwise I'll have to do it when I get a chance. fwiw I think this bump shouldn't be necessary anyway, npm should still install html-minifies 1.3.0 since it falls in the range of `^1.0.0`

**Comment by igoradamenko** [comment]
It looks strange, but an hour ago npm installs wrong version of html-minifier.

Anyway, I can update tests too. Should I just add my case to fixtures & expected files or create new fixture for that?

**Comment by jonschlinkert** [comment]
> Should I just add my case to fixtures & expected files or create new fixture for that?

Sorry, I should have clarified, the tests might not need to be updated. But I know from past experience that (at minimum) when changes are made in html-minifier there are usually minute changes that need to be made in our fixtures. if the tests are passing still then no need to update anything. 

thanks

**Comment by igoradamenko** [comment]
@jonschlinkert Just for restoring a justice: errors were in html-minifier and your package worked good. I've fixed & wrote test for them in this PR: https://github.com/kangax/html-minifier/pull/583 and v.1.3.2 will work fine.

So, you was right about: 
>this bump shouldn't be necessary

Sorry about the confusion and thanks for your patience! :)

**Pull request merged**
